import type { MealPlan } from '@/models/meal-plan';

export const MEAL_PLANS: MealPlan[] = [
  {
    id: 'mp-1',
    date: '2025-12-25',
    meals: [
      {
        id: 'meal-1-1',
        name: 'Oatmeal with Berries',
        type: 'Breakfast',
        items: [
          {
            id: 'item-1-1-1',
            name: 'Rolled Oats',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 300,
              sodium: 100,
              fat: 6,
              protein: 10,
              carbs: 54,
              sugar: 2,
            },
          },
          {
            id: 'item-1-1-2',
            name: 'Mixed Berries',
            units: 0.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 50,
              sodium: 50,
              fat: 2,
              protein: 2,
              carbs: 4,
              sugar: 16,
            },
          },
        ],
      },
      {
        id: 'meal-1-2',
        name: 'Grilled Chicken Salad',
        type: 'Lunch',
        items: [
          {
            id: 'item-1-2-1',
            name: 'Chicken Breast',
            units: 150,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 250,
              sodium: 120,
              fat: 5,
              protein: 35,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-1-2-2',
            name: 'Mixed Greens',
            units: 2,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 170,
              sodium: 360,
              fat: 13,
              protein: 3,
              carbs: 28,
              sugar: 8,
            },
          },
        ],
      },
      {
        id: 'meal-1-3',
        name: 'Salmon with Roasted Vegetables',
        type: 'Dinner',
        items: [
          {
            id: 'item-1-3-1',
            name: 'Salmon Fillet',
            units: 180,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 360,
              sodium: 100,
              fat: 22,
              protein: 40,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-1-3-2',
            name: 'Roasted Vegetables',
            units: 1.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 220,
              sodium: 320,
              fat: 6,
              protein: 5,
              carbs: 35,
              sugar: 12,
            },
          },
        ],
      },
      {
        id: 'meal-1-4',
        name: 'Greek Yogurt with Honey',
        type: 'Snack',
        items: [
          {
            id: 'item-1-4-1',
            name: 'Greek Yogurt',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 180,
              sodium: 75,
              fat: 4,
              protein: 15,
              carbs: 24,
              sugar: 18,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-2',
    date: '2025-12-26',
    meals: [
      {
        id: 'meal-2-1',
        name: 'Scrambled Eggs with Toast',
        type: 'Breakfast',
        items: [
          {
            id: 'item-2-1-1',
            name: 'Eggs',
            units: 3,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 210,
              sodium: 180,
              fat: 15,
              protein: 18,
              carbs: 2,
              sugar: 1,
            },
          },
          {
            id: 'item-2-1-2',
            name: 'Whole Wheat Toast',
            units: 2,
            unitOfMeasure: { id: 'slice', name: 'slice', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 170,
              sodium: 340,
              fat: 3,
              protein: 4,
              carbs: 30,
              sugar: 3,
            },
          },
        ],
      },
      {
        id: 'meal-2-2',
        name: 'Turkey Sandwich',
        type: 'Lunch',
        items: [
          {
            id: 'item-2-2-1',
            name: 'Turkey Breast',
            units: 100,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 120,
              sodium: 420,
              fat: 2,
              protein: 26,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-2-2-2',
            name: 'Whole Grain Bread',
            units: 2,
            unitOfMeasure: { id: 'slice', name: 'slice', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 330,
              sodium: 460,
              fat: 12,
              protein: 6,
              carbs: 48,
              sugar: 8,
            },
          },
        ],
      },
      {
        id: 'meal-2-3',
        name: 'Beef Stir Fry',
        type: 'Dinner',
        items: [
          {
            id: 'item-2-3-1',
            name: 'Beef Sirloin',
            units: 150,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 320,
              sodium: 120,
              fat: 14,
              protein: 42,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-2-3-2',
            name: 'Mixed Vegetables',
            units: 2,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 300,
              sodium: 600,
              fat: 10,
              protein: 6,
              carbs: 52,
              sugar: 10,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-3',
    date: '2025-12-27',
    meals: [
      {
        id: 'meal-3-1',
        name: 'Smoothie Bowl',
        type: 'Breakfast',
        items: [
          {
            id: 'item-3-1-1',
            name: 'Banana',
            units: 2,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 210,
              sodium: 2,
              fat: 1,
              protein: 3,
              carbs: 54,
              sugar: 28,
            },
          },
          {
            id: 'item-3-1-2',
            name: 'Protein Powder',
            units: 1,
            unitOfMeasure: { id: 'scoop', name: 'scoop', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 110,
              sodium: 118,
              fat: 9,
              protein: 12,
              carbs: 6,
              sugar: 0,
            },
          },
        ],
      },
      {
        id: 'meal-3-2',
        name: 'Quinoa Buddha Bowl',
        type: 'Lunch',
        items: [
          {
            id: 'item-3-2-1',
            name: 'Quinoa',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 220,
              sodium: 130,
              fat: 4,
              protein: 8,
              carbs: 40,
              sugar: 2,
            },
          },
          {
            id: 'item-3-2-2',
            name: 'Chickpeas',
            units: 0.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 260,
              sodium: 250,
              fat: 12,
              protein: 16,
              carbs: 22,
              sugar: 6,
            },
          },
        ],
      },
      {
        id: 'meal-3-3',
        name: 'Baked Cod with Sweet Potato',
        type: 'Dinner',
        items: [
          {
            id: 'item-3-3-1',
            name: 'Cod Fillet',
            units: 200,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 180,
              sodium: 120,
              fat: 2,
              protein: 40,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-3-3-2',
            name: 'Sweet Potato',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 340,
              sodium: 220,
              fat: 10,
              protein: 2,
              carbs: 58,
              sugar: 14,
            },
          },
        ],
      },
      {
        id: 'meal-3-4',
        name: 'Apple with Almond Butter',
        type: 'Snack',
        items: [
          {
            id: 'item-3-4-1',
            name: 'Apple',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 95,
              sodium: 2,
              fat: 0,
              protein: 0,
              carbs: 25,
              sugar: 18,
            },
          },
          {
            id: 'item-3-4-2',
            name: 'Almond Butter',
            units: 2,
            unitOfMeasure: { id: 'tbsp', name: 'tablespoon', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 115,
              sodium: 83,
              fat: 12,
              protein: 5,
              carbs: 0,
              sugar: 0,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-4',
    date: '2025-12-28',
    meals: [
      {
        id: 'meal-4-1',
        name: 'Protein Pancakes',
        type: 'Breakfast',
        items: [
          {
            id: 'item-4-1-1',
            name: 'Pancake Mix',
            units: 0.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 310,
              sodium: 230,
              fat: 5,
              protein: 16,
              carbs: 45,
              sugar: 12,
            },
          },
          {
            id: 'item-4-1-2',
            name: 'Protein Powder',
            units: 1,
            unitOfMeasure: { id: 'scoop', name: 'scoop', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 110,
              sodium: 50,
              fat: 9,
              protein: 12,
              carbs: 0,
              sugar: 0,
            },
          },
        ],
      },
      {
        id: 'meal-4-2',
        name: 'Mediterranean Wrap',
        type: 'Lunch',
        items: [
          {
            id: 'item-4-2-1',
            name: 'Whole Wheat Tortilla',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 140,
              sodium: 320,
              fat: 3,
              protein: 5,
              carbs: 24,
              sugar: 1,
            },
          },
          {
            id: 'item-4-2-2',
            name: 'Hummus',
            units: 0.25,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 350,
              sodium: 300,
              fat: 17,
              protein: 21,
              carbs: 28,
              sugar: 5,
            },
          },
        ],
      },
      {
        id: 'meal-4-3',
        name: 'Chicken Pasta Primavera',
        type: 'Dinner',
        items: [
          {
            id: 'item-4-3-1',
            name: 'Chicken Breast',
            units: 120,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 200,
              sodium: 96,
              fat: 4,
              protein: 37,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-4-3-2',
            name: 'Whole Wheat Pasta',
            units: 2,
            unitOfMeasure: { id: 'oz', name: 'ounce', type: 'weight', system: 'customary' },
            nutrition: {
              calories: 440,
              sodium: 484,
              fat: 18,
              protein: 8,
              carbs: 68,
              sugar: 10,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-5',
    date: '2025-12-29',
    meals: [
      {
        id: 'meal-5-1',
        name: 'Avocado Toast with Eggs',
        type: 'Breakfast',
        items: [
          {
            id: 'item-5-1-1',
            name: 'Sourdough Bread',
            units: 2,
            unitOfMeasure: { id: 'slice', name: 'slice', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 160,
              sodium: 320,
              fat: 2,
              protein: 6,
              carbs: 30,
              sugar: 2,
            },
          },
          {
            id: 'item-5-1-2',
            name: 'Avocado',
            units: 0.5,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 120,
              sodium: 10,
              fat: 12,
              protein: 2,
              carbs: 6,
              sugar: 1,
            },
          },
          {
            id: 'item-5-1-3',
            name: 'Eggs',
            units: 2,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 160,
              sodium: 130,
              fat: 10,
              protein: 12,
              carbs: 0,
              sugar: 1,
            },
          },
        ],
      },
      {
        id: 'meal-5-2',
        name: 'Asian Noodle Salad',
        type: 'Lunch',
        items: [
          {
            id: 'item-5-2-1',
            name: 'Rice Noodles',
            units: 2,
            unitOfMeasure: { id: 'oz', name: 'ounce', type: 'weight', system: 'customary' },
            nutrition: {
              calories: 210,
              sodium: 280,
              fat: 1,
              protein: 4,
              carbs: 48,
              sugar: 2,
            },
          },
          {
            id: 'item-5-2-2',
            name: 'Edamame',
            units: 0.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 250,
              sodium: 440,
              fat: 15,
              protein: 18,
              carbs: 10,
              sugar: 10,
            },
          },
        ],
      },
      {
        id: 'meal-5-3',
        name: 'Grilled Pork Chop with Brussels Sprouts',
        type: 'Dinner',
        items: [
          {
            id: 'item-5-3-1',
            name: 'Pork Chop',
            units: 180,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 400,
              sodium: 180,
              fat: 22,
              protein: 48,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-5-3-2',
            name: 'Brussels Sprouts',
            units: 1.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 160,
              sodium: 300,
              fat: 4,
              protein: 4,
              carbs: 28,
              sugar: 8,
            },
          },
        ],
      },
      {
        id: 'meal-5-4',
        name: 'Protein Bar',
        type: 'Snack',
        items: [
          {
            id: 'item-5-4-1',
            name: 'Protein Bar',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 200,
              sodium: 180,
              fat: 8,
              protein: 15,
              carbs: 20,
              sugar: 8,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-6',
    date: '2025-12-30',
    meals: [
      {
        id: 'meal-6-1',
        name: 'Veggie Omelet',
        type: 'Breakfast',
        items: [
          {
            id: 'item-6-1-1',
            name: 'Eggs',
            units: 3,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 210,
              sodium: 180,
              fat: 15,
              protein: 18,
              carbs: 2,
              sugar: 1,
            },
          },
          {
            id: 'item-6-1-2',
            name: 'Mixed Vegetables',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 130,
              sodium: 360,
              fat: 5,
              protein: 6,
              carbs: 14,
              sugar: 5,
            },
          },
        ],
      },
      {
        id: 'meal-6-2',
        name: 'Tuna Salad',
        type: 'Lunch',
        items: [
          {
            id: 'item-6-2-1',
            name: 'Canned Tuna',
            units: 150,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 200,
              sodium: 420,
              fat: 3,
              protein: 32,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-6-2-2',
            name: 'Mixed Greens',
            units: 2,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 180,
              sodium: 200,
              fat: 13,
              protein: 4,
              carbs: 24,
              sugar: 6,
            },
          },
        ],
      },
      {
        id: 'meal-6-3',
        name: 'Shrimp Tacos',
        type: 'Dinner',
        items: [
          {
            id: 'item-6-3-1',
            name: 'Shrimp',
            units: 200,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 200,
              sodium: 380,
              fat: 2,
              protein: 38,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-6-3-2',
            name: 'Corn Tortillas',
            units: 3,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 320,
              sodium: 400,
              fat: 16,
              protein: 0,
              carbs: 52,
              sugar: 6,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-7',
    date: '2025-12-31',
    meals: [
      {
        id: 'meal-7-1',
        name: 'Breakfast Burrito',
        type: 'Breakfast',
        items: [
          {
            id: 'item-7-1-1',
            name: 'Large Tortilla',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 170,
              sodium: 320,
              fat: 4,
              protein: 5,
              carbs: 28,
              sugar: 1,
            },
          },
          {
            id: 'item-7-1-2',
            name: 'Eggs',
            units: 2,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 140,
              sodium: 120,
              fat: 10,
              protein: 12,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-7-1-3',
            name: 'Black Beans',
            units: 0.25,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 210,
              sodium: 240,
              fat: 10,
              protein: 11,
              carbs: 20,
              sugar: 3,
            },
          },
        ],
      },
      {
        id: 'meal-7-2',
        name: 'Chicken Caesar Salad',
        type: 'Lunch',
        items: [
          {
            id: 'item-7-2-1',
            name: 'Chicken Breast',
            units: 150,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 250,
              sodium: 120,
              fat: 5,
              protein: 35,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-7-2-2',
            name: 'Romaine Lettuce',
            units: 2,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 190,
              sodium: 700,
              fat: 17,
              protein: 1,
              carbs: 24,
              sugar: 4,
            },
          },
        ],
      },
      {
        id: 'meal-7-3',
        name: 'Steak with Mashed Potatoes',
        type: 'Dinner',
        items: [
          {
            id: 'item-7-3-1',
            name: 'Ribeye Steak',
            units: 200,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 480,
              sodium: 140,
              fat: 30,
              protein: 52,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-7-3-2',
            name: 'Mashed Potatoes',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 200,
              sodium: 400,
              fat: 2,
              protein: 2,
              carbs: 42,
              sugar: 4,
            },
          },
        ],
      },
      {
        id: 'meal-7-4',
        name: 'Mixed Nuts',
        type: 'Snack',
        items: [
          {
            id: 'item-7-4-1',
            name: 'Mixed Nuts',
            units: 0.25,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 180,
              sodium: 120,
              fat: 16,
              protein: 6,
              carbs: 8,
              sugar: 2,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-8',
    date: '2026-01-01',
    meals: [
      {
        id: 'meal-8-1',
        name: 'Bagel with Cream Cheese',
        type: 'Breakfast',
        items: [
          {
            id: 'item-8-1-1',
            name: 'Whole Wheat Bagel',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 280,
              sodium: 460,
              fat: 2,
              protein: 11,
              carbs: 54,
              sugar: 6,
            },
          },
          {
            id: 'item-8-1-2',
            name: 'Cream Cheese',
            units: 2,
            unitOfMeasure: { id: 'tbsp', name: 'tablespoon', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 100,
              sodium: 80,
              fat: 10,
              protein: 3,
              carbs: 2,
              sugar: 2,
            },
          },
        ],
      },
      {
        id: 'meal-8-2',
        name: 'Veggie Burger',
        type: 'Lunch',
        items: [
          {
            id: 'item-8-2-1',
            name: 'Veggie Patty',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 240,
              sodium: 420,
              fat: 10,
              protein: 20,
              carbs: 18,
              sugar: 4,
            },
          },
          {
            id: 'item-8-2-2',
            name: 'Whole Wheat Bun',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 220,
              sodium: 300,
              fat: 8,
              protein: 4,
              carbs: 34,
              sugar: 6,
            },
          },
        ],
      },
      {
        id: 'meal-8-3',
        name: 'Baked Chicken Thighs with Quinoa',
        type: 'Dinner',
        items: [
          {
            id: 'item-8-3-1',
            name: 'Chicken Thighs',
            units: 200,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 380,
              sodium: 260,
              fat: 22,
              protein: 40,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-8-3-2',
            name: 'Quinoa',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 220,
              sodium: 260,
              fat: 4,
              protein: 8,
              carbs: 44,
              sugar: 6,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-9',
    date: '2026-01-02',
    meals: [
      {
        id: 'meal-9-1',
        name: 'Chia Seed Pudding',
        type: 'Breakfast',
        items: [
          {
            id: 'item-9-1-1',
            name: 'Chia Seeds',
            units: 3,
            unitOfMeasure: { id: 'tbsp', name: 'tablespoon', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 140,
              sodium: 40,
              fat: 9,
              protein: 5,
              carbs: 12,
              sugar: 0,
            },
          },
          {
            id: 'item-9-1-2',
            name: 'Almond Milk',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 140,
              sodium: 100,
              fat: 5,
              protein: 5,
              carbs: 20,
              sugar: 16,
            },
          },
        ],
      },
      {
        id: 'meal-9-2',
        name: 'Caprese Sandwich',
        type: 'Lunch',
        items: [
          {
            id: 'item-9-2-1',
            name: 'Ciabatta Roll',
            units: 1,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 220,
              sodium: 480,
              fat: 3,
              protein: 8,
              carbs: 40,
              sugar: 3,
            },
          },
          {
            id: 'item-9-2-2',
            name: 'Fresh Mozzarella',
            units: 50,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 200,
              sodium: 200,
              fat: 17,
              protein: 10,
              carbs: 4,
              sugar: 3,
            },
          },
        ],
      },
      {
        id: 'meal-9-3',
        name: 'Turkey Meatballs with Zucchini Noodles',
        type: 'Dinner',
        items: [
          {
            id: 'item-9-3-1',
            name: 'Turkey Meatballs',
            units: 5,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 300,
              sodium: 420,
              fat: 16,
              protein: 38,
              carbs: 4,
              sugar: 2,
            },
          },
          {
            id: 'item-9-3-2',
            name: 'Zucchini Noodles',
            units: 2,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 180,
              sodium: 200,
              fat: 4,
              protein: 4,
              carbs: 28,
              sugar: 10,
            },
          },
        ],
      },
      {
        id: 'meal-9-4',
        name: 'Cottage Cheese with Pineapple',
        type: 'Snack',
        items: [
          {
            id: 'item-9-4-1',
            name: 'Cottage Cheese',
            units: 0.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 110,
              sodium: 360,
              fat: 2,
              protein: 14,
              carbs: 8,
              sugar: 6,
            },
          },
          {
            id: 'item-9-4-2',
            name: 'Pineapple Chunks',
            units: 0.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 80,
              sodium: 20,
              fat: 2,
              protein: 2,
              carbs: 16,
              sugar: 12,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mp-10',
    date: '2026-01-03',
    meals: [
      {
        id: 'meal-10-1',
        name: 'French Toast',
        type: 'Breakfast',
        items: [
          {
            id: 'item-10-1-1',
            name: 'Brioche Bread',
            units: 3,
            unitOfMeasure: { id: 'slice', name: 'slice', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 320,
              sodium: 300,
              fat: 6,
              protein: 10,
              carbs: 58,
              sugar: 22,
            },
          },
          {
            id: 'item-10-1-2',
            name: 'Eggs',
            units: 2,
            unitOfMeasure: { id: 'item', name: 'item', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 140,
              sodium: 120,
              fat: 10,
              protein: 8,
              carbs: 4,
              sugar: 2,
            },
          },
        ],
      },
      {
        id: 'meal-10-2',
        name: 'Black Bean Burrito Bowl',
        type: 'Lunch',
        items: [
          {
            id: 'item-10-2-1',
            name: 'Brown Rice',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 220,
              sodium: 280,
              fat: 2,
              protein: 5,
              carbs: 46,
              sugar: 1,
            },
          },
          {
            id: 'item-10-2-2',
            name: 'Black Beans',
            units: 0.5,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 320,
              sodium: 400,
              fat: 16,
              protein: 17,
              carbs: 26,
              sugar: 7,
            },
          },
        ],
      },
      {
        id: 'meal-10-3',
        name: 'Grilled Lamb Chops with Asparagus',
        type: 'Dinner',
        items: [
          {
            id: 'item-10-3-1',
            name: 'Lamb Chops',
            units: 200,
            unitOfMeasure: { id: 'g', name: 'gram', type: 'weight', system: 'metric' },
            nutrition: {
              calories: 520,
              sodium: 380,
              fat: 32,
              protein: 50,
              carbs: 0,
              sugar: 0,
            },
          },
          {
            id: 'item-10-3-2',
            name: 'Asparagus',
            units: 1,
            unitOfMeasure: { id: 'cup', name: 'cup', type: 'volume', system: 'customary' },
            nutrition: {
              calories: 100,
              sodium: 100,
              fat: 2,
              protein: 2,
              carbs: 22,
              sugar: 8,
            },
          },
        ],
      },
      {
        id: 'meal-10-4',
        name: 'Dark Chocolate Square',
        type: 'Snack',
        items: [
          {
            id: 'item-10-4-1',
            name: 'Dark Chocolate',
            units: 2,
            unitOfMeasure: { id: 'square', name: 'square', type: 'quantity', system: 'none' },
            nutrition: {
              calories: 120,
              sodium: 15,
              fat: 8,
              protein: 2,
              carbs: 14,
              sugar: 10,
            },
          },
        ],
      },
    ],
  },
];
