/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CancelButton: typeof import('./components/core/buttons/CancelButton.vue')['default']
    CloseButton: typeof import('./components/core/buttons/CloseButton.vue')['default']
    ConfirmDialog: typeof import('./components/core/ConfirmDialog.vue')['default']
    DailySummaryCard: typeof import('./components/planning/DailySummaryCard.vue')['default']
    DangerButton: typeof import('./components/core/buttons/DangerButton.vue')['default']
    DeleteButton: typeof import('./components/core/buttons/DeleteButton.vue')['default']
    IngredientEditorRow: typeof import('./components/recipes/IngredientEditorRow.vue')['default']
    LoginCard: typeof import('./components/auth/LoginCard.vue')['default']
    MealEditor: typeof import('./components/meals/MealEditor.vue')['default']
    MealItemEditorCard: typeof import('./components/meals/MealItemEditorCard.vue')['default']
    MealItemEditorRows: typeof import('./components/meals/MealItemEditorRows.vue')['default']
    MealView: typeof import('./components/meals/MealView.vue')['default']
    ModifyButton: typeof import('./components/core/buttons/ModifyButton.vue')['default']
    NutritionData: typeof import('./components/portions/NutritionData.vue')['default']
    NutritionEditorRows: typeof import('./components/portions/NutritionEditorRows.vue')['default']
    PrimaryButton: typeof import('./components/core/buttons/PrimaryButton.vue')['default']
    RecipeEditor: typeof import('./components/recipes/RecipeEditor.vue')['default']
    RecipeSummaryCard: typeof import('./components/recipes/RecipeSummaryCard.vue')['default']
    RecipeView: typeof import('./components/recipes/RecipeView.vue')['default']
    ResetButton: typeof import('./components/core/buttons/ResetButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveButton: typeof import('./components/core/buttons/SaveButton.vue')['default']
    SearchInput: typeof import('./components/core/SearchInput.vue')['default']
    SecondaryButton: typeof import('./components/core/buttons/SecondaryButton.vue')['default']
    SettingsEditor: typeof import('./components/settings/SettingsEditor.vue')['default']
    SortableListEditor: typeof import('./components/core/SortableListEditor.vue')['default']
    StepEditorRow: typeof import('./components/recipes/StepEditorRow.vue')['default']
    ViewPageActionButtons: typeof import('./components/core/ViewPageActionButtons.vue')['default']
    WeeklySummaryCard: typeof import('./components/planning/WeeklySummaryCard.vue')['default']
  }
}
