/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error': RouteRecordInfo<
      '/error',
      '/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/foods/': RouteRecordInfo<
      '/foods/',
      '/foods',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/foods/[id]/': RouteRecordInfo<
      '/foods/[id]/',
      '/foods/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/foods/[id]/update': RouteRecordInfo<
      '/foods/[id]/update',
      '/foods/:id/update',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/foods/add': RouteRecordInfo<
      '/foods/add',
      '/foods/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/foods/search-and-add': RouteRecordInfo<
      '/foods/search-and-add',
      '/foods/search-and-add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/planning/': RouteRecordInfo<
      '/planning/',
      '/planning',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/planning/day': RouteRecordInfo<
      '/planning/day',
      '/planning/day',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/planning/week': RouteRecordInfo<
      '/planning/week',
      '/planning/week',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/recipes/': RouteRecordInfo<
      '/recipes/',
      '/recipes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/recipes/[id]/': RouteRecordInfo<
      '/recipes/[id]/',
      '/recipes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/recipes/[id]/update': RouteRecordInfo<
      '/recipes/[id]/update',
      '/recipes/:id/update',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/recipes/add': RouteRecordInfo<
      '/recipes/add',
      '/recipes/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shopping/': RouteRecordInfo<
      '/shopping/',
      '/shopping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/error.vue': {
      routes:
        | '/error'
      views:
        | never
    }
    'src/pages/foods/index.vue': {
      routes:
        | '/foods/'
      views:
        | never
    }
    'src/pages/foods/[id]/index.vue': {
      routes:
        | '/foods/[id]/'
      views:
        | never
    }
    'src/pages/foods/[id]/update.vue': {
      routes:
        | '/foods/[id]/update'
      views:
        | never
    }
    'src/pages/foods/add.vue': {
      routes:
        | '/foods/add'
      views:
        | never
    }
    'src/pages/foods/search-and-add.vue': {
      routes:
        | '/foods/search-and-add'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/planning/index.vue': {
      routes:
        | '/planning/'
      views:
        | never
    }
    'src/pages/planning/day.vue': {
      routes:
        | '/planning/day'
      views:
        | never
    }
    'src/pages/planning/week.vue': {
      routes:
        | '/planning/week'
      views:
        | never
    }
    'src/pages/recipes/index.vue': {
      routes:
        | '/recipes/'
      views:
        | never
    }
    'src/pages/recipes/[id]/index.vue': {
      routes:
        | '/recipes/[id]/'
      views:
        | never
    }
    'src/pages/recipes/[id]/update.vue': {
      routes:
        | '/recipes/[id]/update'
      views:
        | never
    }
    'src/pages/recipes/add.vue': {
      routes:
        | '/recipes/add'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/shopping/index.vue': {
      routes:
        | '/shopping/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
